export type StockParams = {
  period: string;
  stockTotal: number;
  stockIn: number;
  stockOut: number;
  itemDescription: string;
  itemCode: string;
  size: string;
  color: string;
  category: string;
  warehouseName: string;
  warehouseCode: string;
  shelfName: string;
  shelfCode: string;
  rowName: string;
  rowCode: string;
  itemId: string;
  warehouseId: string;
  shelvesId: string;
  rowsId: string;
};
